"""
Permission Action type enum
"""

from enum import StrEnum, unique

@unique
class PermissionActionType(StrEnum):
    """
    Permission action type enum.
    """
    CREATE = 'CREATE'
    READ = 'READ'
    UPDATE = 'UPDATE'
    DELETE = 'DELETE'
    BET = 'BET'
    VERIFY = 'VERIFY'
    CREATE_BET = 'CREATE_BET'
    UPDATE_BET = 'UPDATE_BET'
    DELETE_BET = 'DELETE_BET'
    RESOLVE_BET = 'RESOLVE_BET'
    JOIN_GROUP = 'JOIN_GROUP'
    LEAVE_GROUP = 'LEAVE_GROUP'
    INVITE_USER = 'INVITE_USER'
    REMOVE_USER = 'REMOVE_USER'
    PROMOTE_USER = 'PROMOTE_USER'
    DEMOTE_USER = 'DEMOTE_USER'
    VIEW_GROUP_STATS = 'VIEW_GROUP_STATS'
    MANAGE_FUNDS = 'MANAGE_FUNDS'
    VIEW_HISTORY = 'VIEW_HISTORY'
    EDIT_GROUP_INFO = 'EDIT_GROUP_INFO'
    SET_GROUP_RULES = 'SET_GROUP_RULES'
    LOCK_BET = 'LOCK_BET'
    UNLOCK_BET = 'UNLOCK_BET'
    APPROVE_RESULT = 'APPROVE_RESULT'
    DISPUTE_RESULT = 'DISPUTE_RESULT'
    ASSIGN_ROLE = 'ASSIGN_ROLE'
    REVOKE_ROLE = 'REVOKE_ROLE'
    MUTE_USER = 'MUTE_USER'
    UNMUTE_USER = 'UNMUTE_USER'
    KICK_USER = 'KICK_USER'
    BAN_USER = 'BAN_USER'
    UNBAN_USER = 'UNBAN_USER'
    CREATE_EVENT = 'CREATE_EVENT'
    CLOSE_EVENT = 'CLOSE_EVENT'
    MANAGE_NOTIFICATIONS = 'MANAGE_NOTIFICATIONS'
    MANAGE_PERMISSIONS = 'MANAGE_PERMISSIONS'
    MANAGE_ROLES = 'MANAGE_ROLES'